---
- name: Install Meson build dependencies
  hosts: localhost
    buildDir: builddir
  tasks:
  - name: essential Dependencies
    ansible.builtin.apt:
      pkg:
      - build-essential
      - meson
      - ninja-build
      - gdb
    become: true

  - name: specific Dependencies # https://mesonbuild.com/Tutorial.html
    ansible.builtin.apt:
      pkg:
      - libgtk-3-dev
    become: true

  - name: Meson setup
    ansible.builtin.shell: "meson setup {{ buildDir }}"
    args:
      creates: "{{ buildDir }}"