---
- name: Install Meson build dependencies
  hosts: localhost
  tasks:
  # https://mesonbuild.com/Tutorial.html
  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - build-essential
      - meson
      - ninja-build
      - gdb
      # library: for this
      - libgtk-3-dev
    become: true
